// NOTE: This file assumes the standard structure generated by `flutter create .`
// (run from inside your GitHub Codespace, since Flutter isn't available in
// this scaffolding environment). After running `flutter create .` in the
// project root, MERGE this signingConfigs/buildTypes block into the
// generated android/app/build.gradle.kts — don't just overwrite it, since
// `flutter create` also wires in the Flutter Gradle plugin and applicationId
// that this file doesn't redefine.
//
// See Phase 8.3 of the blueprint for the full GitHub Secrets setup walkthrough
// (keytool keystore generation, Base64 encoding, secret names).

import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    id("kotlin-android")
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services") // required for Firebase
}

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.villagemarket.app" // TODO: replace with your real applicationId
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }

    defaultConfig {
        applicationId = "com.villagemarket.app" // TODO: replace with your real applicationId
        minSdk = 23 // Android 6.0+ — realistic floor for budget rural devices still receiving updates
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        multiDexEnabled = true
    }

    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
            storeFile = keystoreProperties["storeFile"]?.let { rootProject.file(it) }
            storePassword = keystoreProperties["storePassword"] as String?
        }
    }

    buildTypes {
        release {
            // Falls back gracefully to debug signing only if key.properties is
            // missing (e.g. a first local `flutter run` before secrets are
            // configured) — CI always provides key.properties, see Phase 8.2/8.3.
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    implementation(platform("com.google.firebase:firebase-bom:33.6.0"))
    implementation("androidx.multidex:multidex:2.0.1")
}
