// Generated by flutterfire_cli — contains real project values.
// This file is intentionally committed to the repo because the values
// here are project identifiers, NOT secret keys. Security is enforced
// by Firestore Security Rules + App Check (Phase 6 of the blueprint),
// not by keeping this file private.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web platform not configured yet.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS not configured yet — run flutterfire configure.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyAZ02mxGbXtnrD7jZR-TkfoyCC0gQuYCj8',
    appId: '1:694079304143:android:25e6aaa6af39a3377b22ba',
    messagingSenderId: '694079304143',
    projectId: 'shammacity',
    storageBucket: 'shammacity.firebasestorage.app',
  );
}
